### ISSUE TITLE
Crash with circular stratum build dependencies

### ISSUE THREAD

**Issue by ssssam** [devcurmudgeon/ybd#104]
I ran YBD on some definitions where the 'core' stratum build-depended on 'foundation', as well as 'foundation' build-depending on 'core'. It caused this crash:

```
15-07-11 16:00:25 [build-essential] Cache_key is build-essential.d47d41bb446a726ba3695cbff7ac71723eb4289f05d6f140bb4a3bf2ad40aada
15-07-11 16:00:25 [CACHE-KEYS] Elapsed time for cache-key calculations 00:00:04
15-07-11 16:00:25 [TOTAL] Elapsed time 00:00:08
Traceback (most recent call last):
  File "/src/ybd/ybd.py", line 38, in <module>
    cache.get_cache(defs, app.settings['target'])
  File "/src/ybd/cache.py", line 192, in get_cache
    cachedir = os.path.join(app.settings['artifacts'], cache_key(defs, this))
  File "/src/ybd/cache.py", line 53, in cache_key
    hash_factors[factor] = cache_key(defs, factor)
  File "/src/ybd/cache.py", line 53, in cache_key
    hash_factors[factor] = cache_key(defs, factor)
  File "/src/ybd/cache.py", line 50, in cache_key
.... (snip 100s of lines)
    hash_factors[factor] = cache_key(defs, factor)
  File "/src/ybd/cache.py", line 53, in cache_key
    hash_factors[factor] = cache_key(defs, factor)
  File "/src/ybd/cache.py", line 50, in cache_key
    hash_factors[factor] = cache_key(defs, factor)
  File "/src/ybd/cache.py", line 53, in cache_key
    hash_factors[factor] = cache_key(defs, factor)
  File "/src/ybd/cache.py", line 37, in cache_key
    definition = defs.get(this)
  File "/src/ybd/definitions.py", line 170, in get
    if type(definition) is str:
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by devcurmudgeon** [comment]
Fixed in 499120a83d32b2fee2549aa123fb9830f2c0bc53 i think
