### ISSUE TITLE
messy crash if there are no subdirs...

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#108]
15-07-18 09:01:29 [CACHE-KEYS] Elapsed time for cache-key calculations 00:00:00
ls: cannot access */: No such file or directory
15-07-18 09:01:29 [TOTAL] Elapsed time 00:00:00
Traceback (most recent call last):
  File "/src/ybd/ybd.py", line 39, in <module>
    defs.save_trees()
  File "/src/ybd/definitions.py", line 193, in save_trees
    checksum = check_output('ls -lRA */', shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'ls -lRA */' returned non-zero exit status 2
/src/abdef/host # cd ..
/src/abdef # /src/ybd/ybd.py host

**Comment by devcurmudgeon** [comment]
closing this for now... given definitions have been split into subdirs for a very long time
