### ISSUE TITLE
sqlite fail on moonshot...

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#128]
1 15-10-12 00:00:22 [1/720/759] [sqlite3] Running command:
export NOCONFIGURE=1
if [ -e bootstrap ]; then ./bootstrap
elif [ -e bootstrap.sh ]; then ./bootstrap.sh
elif [ -e autogen ]; then ./autogen
elif [ -e autogen.sh ]; then ./autogen.sh
elif [ ! -e ./configure ]; then autoreconf -ivf
fi
./configure --prefix="$PREFIX"
 
1 15-10-12 00:00:22 [1/720/759] [sqlite3] ERROR: command failed in directory /src/definitions:

 sh -c 'export NOCONFIGURE=1
if [ -e bootstrap ]; then ./bootstrap
elif [ -e bootstrap.sh ]; then ./bootstrap.sh
elif [ -e autogen ]; then ./autogen
elif [ -e autogen.sh ]; then ./autogen.sh
elif [ ! -e ./configure ]; then autoreconf -ivf
fi
./configure --prefix="$PREFIX"
'
GIT_NO_REPLACE_OBJECTS=1
HOME=/root
LANG=en_US.UTF-8
LESSCLOSE=/usr/bin/lesspipe %s %s
LESSOPEN=| /usr/bin/lesspipe %s
LOGNAME=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
MAIL=/var/mail/root
OLDPWD=/src
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin:/usr/sbin:/usr/local/sbin
PWD=/src/definitions
SHELL=/bin/bash
SHLVL=3
SUDO_COMMAND=/bin/bash
SUDO_GID=1000
SUDO_UID=1000
SUDO_USER=ubuntu
TERM=xterm-256color
USER=root
USERNAME=root
_=armv7hlf
ldconfig -r /src/tmp/tmpMhifF4
ldconfig: /usr/lib/libstdc++.so.6.0.20-gdb.py is not an ELF file - it has the wrong magic bytes at the start.

# # export NOCONFIGURE=1
if [ -e bootstrap ]; then ./bootstrap
elif [ -e bootstrap.sh ]; then ./bootstrap.sh
elif [ -e autogen ]; then ./autogen
elif [ -e autogen.sh ]; then ./autogen.sh
elif [ ! -e ./configure ]; then autoreconf -ivf
fi
./configure --prefix="$PREFIX"

CCACHE_DIR=/tmp/ccache
CCACHE_EXTRAFILES=
DEFINITIONS_REF=HEAD baserock-15.34-63-gda2d8bc (baserock-15.34 + 63 commits)
DESTDIR=/sqlite3.inst
HOME=/tmp
LC_ALL=C
LOGNAME=tomjon
MORPH_ARCH=armv7lhf
PATH=/usr/bin:/usr/lib/ccache:/usr/bin:/bin:/usr/sbin:/sbin
PREFIX=/usr
PROGRAM_REF=HEAD 15.42 (15.42 + 0 commits)
SHELL=/bin/sh
TARGET=armv7lhf-baserock-linux-gnueabi
TARGET_STAGE1=armv7lhf-bootstrap-linux-gnueabi
TERM=dumb
TZ=UTC
USER=tomjon
USERNAME=tomjon
sh -c 'export NOCONFIGURE=1
if [ -e bootstrap ]; then ./bootstrap
elif [ -e bootstrap.sh ]; then ./bootstrap.sh
elif [ -e autogen ]; then ./autogen
elif [ -e autogen.sh ]; then ./autogen.sh
elif [ ! -e ./configure ]; then autoreconf -ivf
fi
./configure --prefix="$PREFIX"
'
mount(/, MS_PRIVATE | MS_REC): Invalid argument
GIT_NO_REPLACE_OBJECTS=1
HOME=/root
LANG=en_US.UTF-8
LESSCLOSE=/usr/bin/lesspipe %s %s
LESSOPEN=| /usr/bin/lesspipe %s
LOGNAME=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
MAIL=/var/mail/root
OLDPWD=/src
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin:/usr/sbin:/usr/local/sbin
PWD=/src/definitions
SHELL=/bin/bash
SHLVL=3
SUDO_COMMAND=/bin/bash
SUDO_GID=1000
SUDO_UID=1000
SUDO_USER=ubuntu
TERM=xterm-256color
USER=root
USERNAME=root
_=/src/ybd/ybd/sandbox.py
ldconfig -r /src/tmp/tmp_A2gjX
ldconfig: /usr/lib/libstdc++.so.6.0.20-gdb.py is not an ELF file - it has the wrong magic bytes at the start.

# # export NOCONFIGURE=1
if [ -e bootstrap ]; then ./bootstrap
elif [ -e bootstrap.sh ]; then ./bootstrap.sh
elif [ -e autogen ]; then ./autogen
elif [ -e autogen.sh ]; then ./autogen.sh
elif [ ! -e ./configure ]; then autoreconf -ivf
fi
./configure --prefix="$PREFIX"

CCACHE_DIR=/tmp/ccache
CCACHE_EXTRAFILES=
DEFINITIONS_REF=HEAD baserock-15.34-63-gda2d8bc (baserock-15.34 + 63 commits)
DESTDIR=/sqlite3.inst
HOME=/tmp
LC_ALL=C
LOGNAME=tomjon
MORPH_ARCH=armv7lhf
PATH=/usr/bin:/usr/lib/ccache:/usr/bin:/bin:/usr/sbin:/sbin
PREFIX=/usr
PROGRAM_REF=HEAD 15.42-dirty (15.42 + 0 commits)
SHELL=/bin/sh
TARGET=armv7lhf-baserock-linux-gnueabi
TARGET_STAGE1=armv7lhf-bootstrap-linux-gnueabi
TERM=dumb
TZ=UTC
USER=tomjon
USERNAME=tomjon
sh -c 'export NOCONFIGURE=1
if [ -e bootstrap ]; then ./bootstrap
elif [ -e bootstrap.sh ]; then ./bootstrap.sh
elif [ -e autogen ]; then ./autogen
elif [ -e autogen.sh ]; then ./autogen.sh
elif [ ! -e ./configure ]; then autoreconf -ivf
fi
./configure --prefix="$PREFIX"
'
mount(/, MS_PRIVATE | MS_REC): Invalid argument
1 15-10-12 00:00:22 [1/720/759] [sqlite3] ERROR: log file is at /src/artifacts/sqlite3.e9893de9c46ce02898892b7cada538dc84e0b215a2bcfc9bc0cd9ff66f98ac00.build-log.1

1 15-10-12 00:00:22 [1/720/759] [sqlite3] ERROR: sandbox debris is at /src/tmp/tmp_A2gjX

Traceback (most recent call last):
  File "/src/ybd/ybd.py", line 18, in <module>
    runpy.run_module('ybd')
  File "/usr/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/ybd/ybd/__main__.py", line 60, in <module>
    assemble(defs, target)
  File "/src/ybd/ybd/assembly.py", line 61, in assemble
    assemble(defs, system['path'])
  File "/src/ybd/ybd/assembly.py", line 74, in assemble
    preinstall(defs, component, subcomponent)
  File "/src/ybd/ybd/assembly.py", line 127, in preinstall
    preinstall(defs, component, it)
  File "/src/ybd/ybd/assembly.py", line 120, in preinstall
    preinstall(defs, component, it)
  File "/src/ybd/ybd/assembly.py", line 127, in preinstall
    preinstall(defs, component, it)
  File "/src/ybd/ybd/assembly.py", line 120, in preinstall
    preinstall(defs, component, it)
  File "/src/ybd/ybd/assembly.py", line 120, in preinstall
    preinstall(defs, component, it)
  File "/src/ybd/ybd/assembly.py", line 120, in preinstall
    preinstall(defs, component, it)
  File "/src/ybd/ybd/assembly.py", line 120, in preinstall
    preinstall(defs, component, it)
  File "/src/ybd/ybd/assembly.py", line 130, in preinstall
    sandbox.install(defs, component, dependency)
  File "/src/ybd/ybd/sandbox.py", line 68, in install
    unpackdir = cache.get_cache(defs, component) + '.unpacked'
TypeError: unsupported operand type(s) for +: 'bool' and 'str'

**Comment by devcurmudgeon** [comment]
this only occurs with linux-user-chroot. i've amended the default setup instructions to remove l-u-c.
