### ISSUE TITLE
upload fails for kbas on moonshot when run in a chroot...

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#129]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bottle.py", line 763, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 1572, in wrapper
    rv = callback(*a, **ka)
  File "/src/ybd/kbas/__main__.py", line 86, in post_artifact
    upload.save(os.path.join(tmpdir, cache_id))
  File "/usr/lib/python2.7/cgi.py", line 521, in __getattr__
    raise AttributeError, name
AttributeError: save

**Comment by devcurmudgeon** [comment]
Workaround is to run kbas outside the chroot

**Comment by devcurmudgeon** [comment]
not going to fix... kbas should not be run in a chroot...
