### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'bool' and 'str'

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#146]
is usually caused by running as something other than root... but this is an awful error :/

eg

16-01-06 00:00:05 [0/96/96] [systems/minimal-system-x86_64-generic.morph] WARNING: using chroot is less safe than using linux-user-chroot 
16-01-06 00:00:05 [1/96/96] [stage1-binutils] Starting build of stage1-binutils.dac85c48b260aa710b7910ab871bf5b5cce1e27910bf090b4b60bf2dc35fbbbb 
16-01-06 00:00:09 [1/96/96] [stage1-binutils] Git checkout upstream:binutils-tarball in /home/rdale/ybd/tmp/tmpdFZbP5/stage1-binutils.build 
16-01-06 00:00:09 [1/96/96] [stage1-binutils] Upstream version 5500a97a binutils-2.25 (binutils-2.25 + 0 commits) 
16-01-06 00:00:09 [1/96/96] [stage1-binutils] Defined build system is autotools
16-01-06 00:00:09 [1/96/96] [stage1-binutils] Logging build commands to /home/rdale/ybd/artifacts/stage1-binutils.dac85c48b260aa710b7910ab871bf5b5cce1e27910bf090b4b60bf2dc35fbbbb.build-log 
16-01-06 00:00:09 [1/96/96] [stage1-binutils] Running configure-commands
16-01-06 00:00:09 [1/96/96] [stage1-binutils] Running command:
./configure --prefix="$PREFIX" --disable-nls --disable-werror \
  --build=$(sh config.guess) \
  --host=$(sh config.guess) \
  --target=$TARGET_STAGE1 \
  --with-sysroot=/nonexistentdir --with-lib-path="=$PREFIX/lib:=$PREFIX/lib64"
 
Traceback (most recent call last):
  File "/home/rdale/baserock/repos/ybd/ybd/__main__.py", line 61, in <module>
    assemble(defs, target)
  File "/home/rdale/baserock/repos/ybd/ybd/assembly.py", line 91, in assemble
    preinstall(defs, component, subcomponent)
  File "/home/rdale/baserock/repos/ybd/ybd/assembly.py", line 143, in preinstall
    preinstall(defs, component, it)
  File "/home/rdale/baserock/repos/ybd/ybd/assembly.py", line 136, in preinstall
    preinstall(defs, component, it)
  File "/home/rdale/baserock/repos/ybd/ybd/assembly.py", line 136, in preinstall
    preinstall(defs, component, it)
  File "/home/rdale/baserock/repos/ybd/ybd/assembly.py", line 143, in preinstall
    preinstall(defs, component, it)
  File "/home/rdale/baserock/repos/ybd/ybd/assembly.py", line 136, in preinstall
    preinstall(defs, component, it)
  File "/home/rdale/baserock/repos/ybd/ybd/assembly.py", line 143, in preinstall
    preinstall(defs, component, it)
  File "/home/rdale/baserock/repos/ybd/ybd/assembly.py", line 136, in preinstall
    preinstall(defs, component, it)
  File "/home/rdale/baserock/repos/ybd/ybd/assembly.py", line 143, in preinstall
    preinstall(defs, component, it)
  File "/home/rdale/baserock/repos/ybd/ybd/assembly.py", line 136, in preinstall
    preinstall(defs, component, it)
  File "/home/rdale/baserock/repos/ybd/ybd/assembly.py", line 136, in preinstall
    preinstall(defs, component, it)
  File "/home/rdale/baserock/repos/ybd/ybd/assembly.py", line 145, in preinstall
    assemble(defs, dependency)
  File "/home/rdale/baserock/repos/ybd/ybd/assembly.py", line 84, in assemble
    preinstall(defs, component, it)
  File "/home/rdale/baserock/repos/ybd/ybd/assembly.py", line 136, in preinstall
    preinstall(defs, component, it)
  File "/home/rdale/baserock/repos/ybd/ybd/assembly.py", line 146, in preinstall
    sandbox.install(defs, component, dependency)
  File "/home/rdale/baserock/repos/ybd/ybd/sandbox.py", line 64, in install
    unpackdir = cache.get_cache(defs, component) + '.unpacked'
TypeError: unsupported operand type(s) for +: 'bool' and 'str'
16-01-06 00:00:10 [1/96/96] [minimal-system-x86_64-generic] Exiting: uncaught exception

need to make ybd detect this situation and report sensibly...

**Comment by devcurmudgeon** [comment]
should be fixed by ca52aa579c25b
