### ISSUE TITLE
 ERROR: unable to get cache for gettext-tarball

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#149]
this taken from a Concourse instance running on OpenStack...

16-01-11 00:13:12 [24/121/121] [gettext-tarball] Try downloading gettext-tarball.f7b69c52f8594fe36fb43f7ffd697aba27dabb7aced2e08d8c598225948374ab

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
16-01-11 00:15:21 [24/121/121] [gettext-tarball] Problem unpacking /root/ybd/tmp/tmpZDg4DP/gettext-tarball.f7b69c52f8594fe36fb43f7ffd697aba27dabb7aced2e08d8c598225948374ab
16-01-11 00:15:41 [25/121/121] [gettext-tarball] Starting build of gettext-tarball.f7b69c52f8594fe36fb43f7ffd697aba27dabb7aced2e08d8c598225948374ab 
16-01-11 00:16:45 [25/121/121] [gettext-tarball] Try fetching tarball git___git_baserock_org_delta_gettext_tarball.tar 
converted 'http://git.baserock.org/tarballs/git___git_baserock_org_delta_gettext_tarball.tar' (ANSI_X3.4-1968) -> 'http://git.baserock.org/tarballs/git___git_baserock_org_delta_gettext_tarball.tar' (UTF-8)
--2016-01-11 13:56:41--  http://git.baserock.org/tarballs/git___git_baserock_org_delta_gettext_tarball.tar
Resolving git.baserock.org (git.baserock.org)... 185.43.218.183
Connecting to git.baserock.org (git.baserock.org)|185.43.218.183|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14309888 (14M) [application/octet-stream]
Saving to: 'git___git_baserock_org_delta_gettext_tarball.tar'

git___git_baserock_ 100%[=====================>]  13.65M  1.90MB/s   in 7.9s   

2016-01-11 13:56:49 (1.73 MB/s) - 'git___git_baserock_org_delta_gettext_tarball.tar' saved [14309888/14309888]

remote: Counting objects: 8, done.        
remote: Compressing objects: 100% (6/6), done.        
remote: Total 8 (delta 1), reused 0 (delta 0)        
Unpacking objects: 100% (8/8), done.
From git://git.baserock.org/delta/gettext-tarball
 * [new ref]         refs/gitano/admin -> refs/gitano/admin
16-01-11 00:17:02 [25/121/121] [gettext-tarball] Git repo is mirrored at /root/ybd/gits/git___git_baserock_org_delta_gettext_tarball
16-01-11 00:20:07 [25/121/121] [gettext-tarball] Git checkout upstream:gettext-tarball in /root/ybd/tmp/tmpaBpolv/gettext-tarball.build 
16-01-11 00:20:07 [25/121/121] [gettext-tarball] Upstream version 482840e6 gettext-0.19.4 (gettext-0.19.4 + 0 commits) 
16-01-11 00:20:07 [25/121/121] [gettext-tarball] Defined build system is autotools
16-01-11 00:20:07 [25/121/121] [gettext-tarball] Logging build commands to /root/ybd/artifacts/gettext-tarball.f7b69c52f8594fe36fb43f7ffd697aba27dabb7aced2e08d8c598225948374ab.build-log 
16-01-11 00:20:07 [25/121/121] [gettext-tarball] Running configure-commands
16-01-11 00:20:07 [25/121/121] [gettext-tarball] Running command:
./configure --prefix="$PREFIX" 
WARNING: ['umount', '/root/ybd/tmp/tmpaBpolv/dev/shm'] failed: umount: tmpfs: mountpoint not found

WARNING: ['umount', '/root/ybd/tmp/tmpaBpolv/proc'] failed: umount: proc: mountpoint not found

16-01-11 00:34:02 [25/121/121] [gettext-tarball] Running build-commands
16-01-11 00:34:02 [25/121/121] [gettext-tarball] Running command:
make 
16-01-11 00:34:02 [25/121/121] [SETUP] WARNING: unable to remove /root/ybd/tmp/tmpaBpolv

16-01-11 00:34:02 [25/121/121] [base-system-x86_64-generic] ERROR: unable to get cache for gettext-tarball

**Comment by devcurmudgeon** [comment]
looks like this was triggered by a broken artifact from the cache... need to
- trace this path and fix it
- provide a way to invalidate/fix broken artifact items.

**Comment by devcurmudgeon** [comment]
wrt "provide a way to invalidate/fix broken artifact items", kbas already verifies that it can untar the artifact   so it shouldn't be possible to have a broken artifact. further checking shows the published get text artifact is actually ok, so the "tar: Unexpected EOF in archive" is probably due to a network fail.

**Comment by devcurmudgeon** [comment]
the warnings about umount failing suggest that mounting tmpfs and proc didn't happen... which is weird

**Comment by devcurmudgeon** [comment]
so after 2de5296 , exceptions don't get eaten and we can see the following... which may be sandboxlib or something to do with how Concourse/docker containment is working?

16-01-12 03:34:52 [14/121/121] [linux-api-headers] Running command:
case "$MORPH_ARCH" in
    armv5l)
        ARCH="arm" ;;
    armv7b|armv7l|armv7lhf)
        ARCH="arm" ;;
    armv8l64|armv8b64)
        ARCH="arm64" ;;
    x86_32)
        ARCH="i386" ;;
    x86_64)
        ARCH="x86_64" ;;
    ppc64)
        ARCH="powerpc" ;;
    *)
        echo "Error: unsupported Morph architecture: $MORPH_ARCH" >&2
        exit 1
esac
ARCH=$ARCH make INSTALL_HDR_PATH=dest headers_install
 
WARNING: ['umount', '/root/ybd/tmp/tmpSuZip3/dev/shm'] failed: umount: tmpfs: mountpoint not found

WARNING: ['umount', '/root/ybd/tmp/tmpSuZip3/proc'] failed: umount: proc: mountpoint not found

16-01-12 03:38:44 [14/121/121] [linux-api-headers] Running command:
install -d "$DESTDIR${PREFIX-/usr}/include" 
Traceback (most recent call last):
  File "/tmp/build/641c0e3f-a9d8-4e7f-5533-e94ca07e9810/ybd/ybd/__main__.py", line 65, in <module>
    assemble(defs, target)
  File "/tmp/build/641c0e3f-a9d8-4e7f-5533-e94ca07e9810/ybd/ybd/assembly.py", line 92, in assemble
    preinstall(defs, component, subcomponent)
  File "/tmp/build/641c0e3f-a9d8-4e7f-5533-e94ca07e9810/ybd/ybd/assembly.py", line 154, in preinstall
    preinstall(defs, component, it)
  File "/tmp/build/641c0e3f-a9d8-4e7f-5533-e94ca07e9810/ybd/ybd/assembly.py", line 147, in preinstall
    preinstall(defs, component, it)
  File "/tmp/build/641c0e3f-a9d8-4e7f-5533-e94ca07e9810/ybd/ybd/assembly.py", line 147, in preinstall
    preinstall(defs, component, it)
  File "/tmp/build/641c0e3f-a9d8-4e7f-5533-e94ca07e9810/ybd/ybd/assembly.py", line 154, in preinstall
    preinstall(defs, component, it)
  File "/tmp/build/641c0e3f-a9d8-4e7f-5533-e94ca07e9810/ybd/ybd/assembly.py", line 147, in preinstall
    preinstall(defs, component, it)
  File "/tmp/build/641c0e3f-a9d8-4e7f-5533-e94ca07e9810/ybd/ybd/assembly.py", line 154, in preinstall
    preinstall(defs, component, it)
  File "/tmp/build/641c0e3f-a9d8-4e7f-5533-e94ca07e9810/ybd/ybd/assembly.py", line 147, in preinstall
    preinstall(defs, component, it)
  File "/tmp/build/641c0e3f-a9d8-4e7f-5533-e94ca07e9810/ybd/ybd/assembly.py", line 154, in preinstall
    preinstall(defs, component, it)
  File "/tmp/build/641c0e3f-a9d8-4e7f-5533-e94ca07e9810/ybd/ybd/assembly.py", line 156, in preinstall
    assemble(defs, dependency)
  File "/tmp/build/641c0e3f-a9d8-4e7f-5533-e94ca07e9810/ybd/ybd/assembly.py", line 101, in assemble
    do_build(defs, component)
  File "/tmp/build/641c0e3f-a9d8-4e7f-5533-e94ca07e9810/ybd/ybd/assembly.py", line 111, in do_build
    build(defs, component)
  File "/tmp/build/641c0e3f-a9d8-4e7f-5533-e94ca07e9810/ybd/ybd/assembly.py", line 187, in build
    allow_parallel=('build' in build_step))
  File "/tmp/build/641c0e3f-a9d8-4e7f-5533-e94ca07e9810/ybd/ybd/sandbox.py", line 155, in run_sandboxed
    env=env, **config)
  File "/usr/local/lib/python2.7/dist-packages/sandboxlib/chroot.py", line 227, in run_sandbox_with_redirection
    exit, out, err = run_sandbox(command, **sandbox_config)
  File "/usr/local/lib/python2.7/dist-packages/sandboxlib/chroot.py", line 208, in run_sandbox
    with mount_all(filesystem_root, extra_mounts):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/sandboxlib/chroot.py", line 139, in mount_all
    mount(source, path, mount_type, mount_options)
  File "/usr/local/lib/python2.7/dist-packages/sandboxlib/chroot.py", line 112, in mount
    argv, err.decode('utf-8')))
RuntimeError: ['mount', '-t', 'proc', '-o', '', '', '/root/ybd/tmp/tmpSuZip3/proc'] failed: mount:  is already mounted or /root/ybd/tmp/tmpSuZip3/proc busy

**Comment by devcurmudgeon** [comment]
from discussion on #baserock, it's notable that this is the first component that's actually sandboxed (stage1 and stage2 are not)

**Comment by devcurmudgeon** [comment]
Fixed by@benjamb, thanks!
