### ISSUE TITLE
16.05 uncaught exception building ci.morph on ARMv7

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#152]
0 16-02-06 00:15:20 [25/78/418] [x-common] Starting build of x-common.23eb4733f22d4d6a7f2f7113ff239196c7da53f2c0045de1ac640d9b7122db65 
0 16-02-06 00:15:20 [25/78/418] [x-common] No /src/tmp/tmprUpdME/etc/ld.so.conf, not running ldconfig 
0 16-02-06 00:15:20 [25/78/418] [x-common] Defined build system is manual
0 16-02-06 00:15:20 [25/78/418] [x-common] Logging build commands to /src/artifacts/x-common.23eb4733f22d4d6a7f2f7113ff239196c7da53f2c0045de1ac640d9b7122db65.build-log.0 
0 16-02-06 00:15:20 [25/78/418] [x-common] Elapsed time for build of x-common.23eb4733f22d4d6a7f2f7113ff239196c7da53f2c0045de1ac640d9b7122db65 00:00:00
0 16-02-06 00:15:20 [25/78/418] [x-common] Starting artifact creation 
0 16-02-06 00:15:20 [25/78/418] [x-common] splitting stratum 
0 16-02-06 00:15:20 [25/78/418] [xorg-lib-libxshmfence] loaded metadata for xorg-lib-libxshmfence
0 16-02-06 00:15:20 [25/78/418] [xorg-lib-libXau] loaded metadata for xorg-lib-libXau
0 16-02-06 00:15:20 [25/78/418] [xorg-proto-presentproto] WARNING: problem loading metadata /src/artifacts/xorg-proto-presentproto.4b3fdb02ffdc25e99ef3e8a9178b7bdfb8f7283e129bd741191041a924800614/xorg-proto-presentproto.4b3fdb02ffdc25e99ef3e8a9178b7bdfb8f7283e129bd741191041a924800614.unpacked/baserock/xorg-proto-presentproto.meta
0 16-02-06 00:15:22 [25/78/418] [FOO] except-exception 
Traceback (most recent call last):
  File "/src/ybd/ybd/__main__.py", line 66, in <module>
    compose(defs, target)
  File "/src/ybd/ybd/assembly.py", line 81, in compose
    assemble(defs, component)  # bring in 'contents' recursively
  File "/src/ybd/ybd/assembly.py", line 92, in assemble
    compose(defs, system['path'])
  File "/src/ybd/ybd/assembly.py", line 81, in compose
    assemble(defs, component)  # bring in 'contents' recursively
  File "/src/ybd/ybd/assembly.py", line 96, in assemble
    install_contents(defs, component)
  File "/src/ybd/ybd/assembly.py", line 229, in install_contents
    install(defs, component, contents)
  File "/src/ybd/ybd/assembly.py", line 220, in install
    install(defs, component, content.get('contents', []))
  File "/src/ybd/ybd/assembly.py", line 221, in install
    compose(defs, content)
  File "/src/ybd/ybd/assembly.py", line 82, in compose
    build(defs, component)     # bring in 'build-depends', and run make
  File "/src/ybd/ybd/assembly.py", line 107, in build
    install_dependencies(defs, component)
  File "/src/ybd/ybd/assembly.py", line 261, in install_dependencies
    install(defs, component, dependencies)
  File "/src/ybd/ybd/assembly.py", line 252, in install
    compose(defs, dependency)
  File "/src/ybd/ybd/assembly.py", line 82, in compose
    build(defs, component)     # bring in 'build-depends', and run make
  File "/src/ybd/ybd/assembly.py", line 116, in build
    splitting.write_stratum_metafiles(defs, component)
  File "/src/ybd/ybd/splitting.py", line 235, in write_stratum_metafiles
    split_metadata['ref'] = metadata['ref']
TypeError: 'NoneType' object has no attribute '__getitem__'
0 16-02-06 00:15:22 [25/78/418] [ci] Exiting: uncaught exception

**Comment by devcurmudgeon** [comment]
I should have tested backwards compatibility on existing artifacts. as of 16.06, we have artifact-version: 1
