### ISSUE TITLE
deploy fails with KeyError: 'sandbox'

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#158]
16-02-09 00:00:06 [0/6/97] [minimal-system-deploy] Starting cluster deployment 
16-02-09 00:00:06 [0/6/97] [systems-minimal-system-x86_64-generic.morph] Starting deployment 
Traceback (most recent call last):
  File "/src/ybd/ybd.py", line 18, in <module>
    runpy.run_module('ybd')
  File "/usr/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/ybd/ybd/__main__.py", line 89, in <module>
    deploy(defs, target)
  File "/src/ybd/ybd/deployment.py", line 31, in deploy
    deploy_system(defs, system)
  File "/src/ybd/ybd/deployment.py", line 48, in deploy_system
    app.log(system, 'Extracting system artifact into', system['sandbox'])
KeyError: 'sandbox'

**Comment by devcurmudgeon** [comment]
fixed in a3d80e0afb56be6f40fb789526e119fd54cbdc1
