### ISSUE TITLE
occasional early uncaught exception...

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#164]
3 16-02-12 00:00:10 [0/567/571] [FORKS] I am fork 3
Traceback (most recent call last):
  File "/src/ybd/ybd/__main__.py", line 69, in <module>
    compose(defs, target)
  File "/src/ybd/ybd/assembly.py", line 81, in compose
    return cache_key(defs, component)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/src/ybd/ybd/assembly.py", line 196, in claim
    os.remove(lockfile(defs, this))
OSError: [Errno 2] No such file or directory: '/src/tmp/ci.f618d2d35dc9f9bb968c164c4fd78f18697001edba7495078b15d254c286a615.lock'
2 16-02-12 00:00:10 [0/567/571] [ci] Exiting: uncaught exception

**Comment by devcurmudgeon** [comment]
and again...

Traceback (most recent call last):
  File "/src/ybd/ybd/__main__.py", line 69, in <module>
    compose(defs, target)
  File "/src/ybd/ybd/assembly.py", line 81, in compose
    return cache_key(defs, component)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/src/ybd/ybd/assembly.py", line 191, in claim
    os.remove(lockfile(defs, this))
OSError: [Errno 2] No such file or directory: '/src/tmp/ci.af51c54b1e483df34e8ae83ad86c2186068ec6cbf7830c3a5c6deca2a4e48598.lock'
