### ISSUE TITLE
count becomes non-integer?

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#175]
3 16-02-18 00:01:21 [/968/969] [simplejson] Cached 137718 bytes b333128c10687abfd54cc777723e5f72 as simplejson.5069ce227924690d825f37342a325d1c5468e82a56861fbf813ea61acb309f6c
2 16-02-18 00:01:21 [/968/969] [xorg-driver-xf86-video-fbdev] Try downloading xorg-driver-xf86-video-fbdev.96bd8e45c8e8ac1f88cc67235eba7f8761afc016c0ed5758f6a99e5f456b2a83
1 16-02-18 00:01:21 [/968/969] [python-cheetah] Cached 355343 bytes 60956fc5f8abf2e4f6c5a925c8a356f1 as python-cheetah.967288d363627095e8ab289232170ff34995e580852f06d70542dffc07813739
Traceback (most recent call last):
  File "/src/ybd/ybd/__main__.py", line 69, in <module>
    compose(defs, target)
  File "/src/ybd/ybd/assembly.py", line 87, in compose
    assemble(defs, component)  # bring in 'contents' recursively
  File "/src/ybd/ybd/assembly.py", line 98, in assemble
    compose(defs, system['path'])
  File "/src/ybd/ybd/assembly.py", line 87, in compose
    assemble(defs, component)  # bring in 'contents' recursively
  File "/src/ybd/ybd/assembly.py", line 102, in assemble
    install_contents(defs, component)
  File "/src/ybd/ybd/assembly.py", line 239, in install_contents
    install(defs, component, contents)
  File "/src/ybd/ybd/assembly.py", line 230, in install
    install(defs, component, content.get('contents', []))
  File "/src/ybd/ybd/assembly.py", line 231, in install
    compose(defs, content)
  File "/src/ybd/ybd/assembly.py", line 80, in compose
    app.config['counter'].increment()
  File "/src/ybd/ybd/app.py", line 51, in increment
    f.write(str(int(count) + 1))
ValueError: invalid literal for int() with base 10: ''

**Comment by devcurmudgeon** [comment]
well, it fixed the crash, but

1 16-02-18 00:29:13 [416/330/977] [udisks] Running command:

**Comment by devcurmudgeon** [comment]
Fixed with c03a482e0f7657f07241a441fd637fb5a2e29f06 and 4c975411db9a65b5c8e6f12bc20e26d774e1738b

**Comment by devcurmudgeon** [comment]
Not fixed...
