### ISSUE TITLE
'ascii' codec can't encode characters in position 99-100: ordinal not in range(128)

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#182]
16-03-02 00:04:35 [2/237/288] [ca-certificates] splitting chunk 
Traceback (most recent call last):
  File "/src/workspace/baserock-15.10/baserock/baserock/ybd/ybd/__main__.py", line 69, in <module>
    compose(defs, target)
  File "/src/workspace/baserock-15.10/baserock/baserock/ybd/ybd/assembly.py", line 81, in compose
    assemble(defs, component)  # bring in 'contents' recursively
  File "/src/workspace/baserock-15.10/baserock/baserock/ybd/ybd/assembly.py", line 96, in assemble
    install_contents(defs, component)
  File "/src/workspace/baserock-15.10/baserock/baserock/ybd/ybd/assembly.py", line 222, in install_contents
    install(defs, component, contents)
  File "/src/workspace/baserock-15.10/baserock/baserock/ybd/ybd/assembly.py", line 213, in install
    install(defs, component, content.get('contents', []))
  File "/src/workspace/baserock-15.10/baserock/baserock/ybd/ybd/assembly.py", line 214, in install
    compose(defs, content)
  File "/src/workspace/baserock-15.10/baserock/baserock/ybd/ybd/assembly.py", line 82, in compose
    build(defs, component)     # bring in 'build-depends', and run make
  File "/src/workspace/baserock-15.10/baserock/baserock/ybd/ybd/assembly.py", line 112, in build
    splitting.write_metadata(defs, component)
  File "/src/workspace/baserock-15.10/baserock/baserock/ybd/ybd/splitting.py", line 119, in write_metadata
    write_chunk_metafile(defs, component)
  File "/src/workspace/baserock-15.10/baserock/baserock/ybd/ybd/splitting.py", line 154, in write_chunk_metafile
    for path in files:
  File "/usr/lib/python2.7/site-packages/fs/base.py", line 1068, in walkfiles
    for path, files in self.walk(normpath(path), wildcard=wildcard, dir_wildcard=dir_wildcard, search=search, ignore_errors=ignore_errors):
  File "/usr/lib/python2.7/site-packages/fs/base.py", line 1037, in walk
    for p in recurse(path):
  File "/usr/lib/python2.7/site-packages/fs/base.py", line 1030, in recurse
    for p in recurse(path):
  File "/usr/lib/python2.7/site-packages/fs/base.py", line 1030, in recurse
    for p in recurse(path):
  File "/usr/lib/python2.7/site-packages/fs/base.py", line 1030, in recurse
    for p in recurse(path):
  File "/usr/lib/python2.7/site-packages/fs/base.py", line 1030, in recurse
    for p in recurse(path):
  File "/usr/lib/python2.7/site-packages/fs/base.py", line 1029, in recurse
    for path in listdir(recurse_path, wildcard=dir_wildcard, full=True, dirs_only=True):
  File "/usr/lib/python2.7/site-packages/fs/base.py", line 987, in listdir
    return self.listdir(path, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fs/errors.py", line 257, in wrapper
    return func(self,*args,**kwds)
  File "/usr/lib/python2.7/site-packages/fs/osfs/__init__.py", line 250, in listdir
    return self._listdir_helper(path, paths, wildcard, full, absolute, dirs_only, files_only)
  File "/usr/lib/python2.7/site-packages/fs/base.py", line 570, in _listdir_helper
    entries = [p for p in entries if isdir(pathcombine(path, p))]
  File "/usr/lib/python2.7/site-packages/fs/errors.py", line 257, in wrapper
    return func(self,*args,**kwds)
  File "/usr/lib/python2.7/site-packages/fs/osfs/__init__.py", line 240, in isdir
    return _isdir(self.getsyspath(path))
  File "/usr/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 99-100: ordinal not in range(128)
16-03-02 00:04:37 [2/237/288] [weston-system-x86_64-generic] Exiting: uncaught exception

**Comment by devcurmudgeon** [comment]
i think this is the same as #218
