### ISSUE TITLE
mount: cannot mount block device tmpfs read-only (on gitlab-ci)

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#192]
16-03-13 00:10:01 [30/984/984] [minimal-system-x86_64-generic] Running command:
if which depmod; then (cd /lib/modules && for version in *; do depmod -a "$version"; done) fi 
Traceback (most recent call last):
  File "/builds/Sherwood/ybd/ybd/__main__.py", line 74, in <module>
    compose(defs, target)
  File "/builds/Sherwood/ybd/ybd/assembly.py", line 82, in compose
    assemble(defs, component)  # bring in 'contents' recursively
  File "/builds/Sherwood/ybd/ybd/assembly.py", line 93, in assemble
    compose(defs, system['path'])
  File "/builds/Sherwood/ybd/ybd/assembly.py", line 83, in compose
    build(defs, component)     # bring in 'build-depends', and run make
  File "/builds/Sherwood/ybd/ybd/assembly.py", line 110, in build
    run_build(defs, component)
  File "/builds/Sherwood/ybd/ybd/assembly.py", line 148, in run_build
    allow_parallel=('build' in build_step))
  File "/builds/Sherwood/ybd/ybd/sandbox.py", line 163, in run_sandboxed
    env=env, **config)
  File "/usr/local/lib/python2.7/dist-packages/sandboxlib/chroot.py", line 227, in run_sandbox_with_redirection
    exit, out, err = run_sandbox(command, **sandbox_config)
  File "/usr/local/lib/python2.7/dist-packages/sandboxlib/chroot.py", line 208, in run_sandbox
    with mount_all(filesystem_root, extra_mounts):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/sandboxlib/chroot.py", line 139, in mount_all
    mount(source, path, mount_type, mount_options)
  File "/usr/local/lib/python2.7/dist-packages/sandboxlib/chroot.py", line 112, in mount
    argv, err.decode('utf-8')))
RuntimeError: ['mount', '-t', 'tmpfs', '-o', '', 'tmpfs', '/src/tmp/tmpjOC7FI/dev/shm'] failed: mount: block device tmpfs is write-protected, mounting read-only
mount: cannot mount block device tmpfs read-only

16-03-13 00:10:01 [30/984/984] [ci] Exiting: uncaught exception

**Comment by devcurmudgeon** [comment]
i believe folks are happily using ybd with gitlab-ci now, so closing this...
