### ISSUE TITLE
app exception on deploy upgrade....

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#20]
/src/workspace/reference/baserock/baserock/definitions # python /src/ybd/ybd.py clusters/upgrade-devel.morph x86_64
...
gives...

2015-04-20 10:30:16 [upgrade-devel.devel-system-x86_64-generic@fd422f129b76b4b2ef9ed16ec07d8663fb7ecd20ced4b0fc3bfaafd17dcc2153.self] Start deployment 
2015-04-20 10:30:16 [upgrade-devel.devel-system-x86_64-generic@fd422f129b76b4b2ef9ed16ec07d8663fb7ecd20ced4b0fc3bfaafd17dcc2153.self] Staging deployment in /src/tmp/deployments/tmpfNuOMJ 
2015-04-20 10:30:16 [upgrade-devel.devel-system-x86_64-generic@fd422f129b76b4b2ef9ed16ec07d8663fb7ecd20ced4b0fc3bfaafd17dcc2153.self] Running write method pre-check: ['/usr/lib/python2.7/site-packages/morphlib/exts/ssh-rsync.check', 'root@127.0.0.1'] 
CRITICAL:root:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cliapp/app.py", line 190, in _run
    self.process_args(args)
  File "/src/tmp/tmpHsol7R", line 33, in process_args
    'The ssh-rsync write is for upgrading existing remote '
AppException: The ssh-rsync write is for upgrading existing remote Baserock machines. It cannot be used for an initial deployment.

ERROR: The ssh-rsync write is for upgrading existing remote Baserock machines. It cannot be used for an initial deployment.

**Comment by devcurmudgeon** [comment]
this is partially fixed by 9a8eb839e254e5999b6699959c51055f1fbd9c20, but there's still a long way to go on deploy.
