### ISSUE TITLE
groff sandbox copy failure...

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#209]
on an x86_32 vm....

16-04-25 00:01:22 [0/56/337] [foo.morph] WARNING: using chroot is less safe than using linux-user-chroot 
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/7bb39ef9/0/codethink/definitions/ybd/ybd/splitting.py", line 95, in install_stratum_artifacts
    utils.copy_file_list(path, component['sandbox'], filelist)
  File "/home/gitlab-runner/builds/7bb39ef9/0/codethink/definitions/ybd/ybd/utils.py", line 148, in copy_file_list
    _process_list(srcpath, destpath, filelist, _copyfun)
  File "/home/gitlab-runner/builds/7bb39ef9/0/codethink/definitions/ybd/ybd/utils.py", line 190, in _process_list
    _copy_directories(srcdir, destdir, path)
  File "/home/gitlab-runner/builds/7bb39ef9/0/codethink/definitions/ybd/ybd/utils.py", line 180, in _copy_directories
    'directory expected: %s' % dir)
IOError: Source directory tree has file where directory expected: usr/share/groff/current
16-04-25 00:01:34 [0/56/337] [foundation] ERROR: failed copying files from /home/gitlab-runner/ybd/artifacts/groff.df8b3ed5586f35e1587a4a6fd3b09a3c7a04caba8b2aa932092d9a26af8d616e/groff.df8b3ed5586f35e1587a4a6fd3b09a3c7a04caba8b2aa932092d9a26af8d616e.unpacked/baserock/groff.meta

16-04-25 00:01:34 [0/56/337] [foundation] ERROR: sandbox debris is at /home/gitlab-runner/ybd/tmp/tmpAIaWgB

**Comment by devcurmudgeon** [comment]
can't reproduce, closing now
