### ISSUE TITLE
can't create minimal system...

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#211]
16-04-27 00:00:04 [0/1/96] [minimal-system-x86_64-generic] ERROR: a surprise exception happened 
Traceback (most recent call last):
  File "/src/ybd/ybd/sandbox.py", line 60, in setup
    yield
  File "/src/ybd/ybd/assembly.py", line 64, in compose
    build(defs, component)     # bring in 'build-depends', and run make
  File "/src/ybd/ybd/assembly.py", line 91, in build
    run_build(defs, component)
  File "/src/ybd/ybd/assembly.py", line 127, in run_build
    allow_parallel=('build' in build_step))
  File "/src/ybd/ybd/sandbox.py", line 174, in run_sandboxed
    env=env, **config)
  File "/usr/local/lib/python2.7/site-packages/sandboxlib/chroot.py", line 227, in run_sandbox_with_redirection
    exit, out, err = run_sandbox(command, **sandbox_config)
  File "/usr/local/lib/python2.7/site-packages/sandboxlib/chroot.py", line 223, in run_sandbox
    raise exception
LookupError: unknown encoding: string-escape

16-04-27 00:00:04 [0/1/96] [minimal-system-x86_64-generic] ERROR: sandbox debris is at /src/tmp/tmpscoQgn

**Comment by devcurmudgeon** [comment]
can't reproduce since 16.20 - closing this.
