### ISSUE TITLE
integration commands fail on [-runtime] split systems

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#224]
If i set default-splits: [-runtime] and then try to build base-system-x86_64-generic, it fails with the following...

16-06-03 00:00:03 [0/11/124] [CACHE-KEYS] [ ] bsp-x86_64-generic.62c2daccc9c8fdf7fc849ed550377937663d9013ddb203e04009e666d3e90dc5
16-06-03 00:00:03 [0/12/125] [CACHE-KEYS] [ ] base-system-x86_64-generic.e77ea70e71455a360ad63d5dfc00e8113cde717fc1938de56430940995b1884f
16-06-03 00:00:03 [0/12/125] [CACHE-KEYS] Elapsed time for cache-key calculations 00:00:00
16-06-03 00:00:03 [0/12/125] [SETUP] 13GB is enough free space 
16-06-03 00:00:03 [0/12/125] [systems/base-system-x86_64-generic.morph] Sandbox using <module 'sandboxlib.chroot' from '/usr/local/lib/python2.7/dist-packages/sandboxlib/chroot.pyc'> 
16-06-03 00:00:03 [0/12/125] [systems/base-system-x86_64-generic.morph] WARNING: using chroot is less safe than using linux-user-chroot 
16-06-03 00:00:03 [0/12/125] [build-essential] Starting build of build-essential.208f09fb4df35ec3e8d6540903572b0794bb895f1f52125e420223fd51b7f67c 
16-06-03 00:00:03 [0/12/125] [build-essential] Defined build system is manual
16-06-03 00:00:03 [0/12/125] [build-essential] Logging build commands to /src/artifacts/build-essential.208f09fb4df35ec3e8d6540903572b0794bb895f1f52125e420223fd51b7f67c.build-log 
16-06-03 00:00:03 [0/12/125] [build-essential] Elapsed time for build of build-essential.208f09fb4df35ec3e8d6540903572b0794bb895f1f52125e420223fd51b7f67c 00:00:00
16-06-03 00:00:03 [0/12/125] [build-essential] Starting artifact creation 
16-06-03 00:00:03 [0/12/125] [build-essential] Splitting stratum
16-06-03 00:00:04 [0/12/125] [build-essential] WARNING: overlapping path /usr/bin/awk
16-06-03 00:00:04 [0/12/125] [gawk.meta] WARNING: overlap at usr/bin/awk
16-06-03 00:00:04 [0/12/125] [busybox.meta] WARNING: overlap at usr/bin/awk
16-06-03 00:00:04 [1/12/125] [build-essential] Cached 35579 bytes 023bb9510da2d13e61f9a1c4be7f3f19 as build-essential.208f09fb4df35ec3e8d6540903572b0794bb895f1f52125e420223fd51b7f67c
16-06-03 00:00:04 [1/12/125] [build-essential] Elapsed time for artifact creation 00:00:00
16-06-03 00:00:04 [1/12/125] [base-system-x86_64-generic] Installing build-essential splits ['build-essential-runtime']
16-06-03 00:00:05 [1/12/125] [core] Starting build of core.b036a5d9d7d657e69f14b6294dbf6ae2d612dafe0a3b852928984ab476c489c5 
16-06-03 00:00:05 [1/12/125] [core] No /src/tmp/tmp7lapj7/etc/ld.so.conf, not running ldconfig 
16-06-03 00:00:05 [1/12/125] [core] Defined build system is manual
16-06-03 00:00:05 [1/12/125] [core] Logging build commands to /src/artifacts/core.b036a5d9d7d657e69f14b6294dbf6ae2d612dafe0a3b852928984ab476c489c5.build-log 
16-06-03 00:00:05 [1/12/125] [core] Elapsed time for build of core.b036a5d9d7d657e69f14b6294dbf6ae2d612dafe0a3b852928984ab476c489c5 00:00:00
16-06-03 00:00:05 [1/12/125] [core] Starting artifact creation 
16-06-03 00:00:05 [1/12/125] [core] Splitting stratum
16-06-03 00:00:08 [1/12/125] [core] WARNING: overlapping path /usr/lib/libltdl.so.7
16-06-03 00:00:08 [1/12/125] [libtool-tarball.meta] WARNING: overlap at usr/lib/libltdl.so.7
16-06-03 00:00:08 [1/12/125] [libtool.meta] WARNING: overlap at usr/lib/libltdl.so.7
16-06-03 00:00:08 [1/12/125] [core] WARNING: overlapping path /usr/lib/libltdl.so
16-06-03 00:00:08 [1/12/125] [libtool-tarball.meta] WARNING: overlap at usr/lib/libltdl.so
16-06-03 00:00:08 [1/12/125] [libtool.meta] WARNING: overlap at usr/lib/libltdl.so
16-06-03 00:00:08 [2/12/125] [core] Cached 116032 bytes b6d9075137a1352147ee2c290b4b01b3 as core.b036a5d9d7d657e69f14b6294dbf6ae2d612dafe0a3b852928984ab476c489c5
16-06-03 00:00:08 [2/12/125] [core] Elapsed time for artifact creation 00:00:02
16-06-03 00:00:08 [2/12/125] [base-system-x86_64-generic] Installing core splits ['core-runtime']
16-06-03 00:00:14 [2/12/125] [base-system-x86_64-generic] Installing foundation splits ['foundation-runtime']
16-06-03 00:00:15 [2/12/125] [bsp-x86_64-generic] Starting build of bsp-x86_64-generic.62c2daccc9c8fdf7fc849ed550377937663d9013ddb203e04009e666d3e90dc5 
16-06-03 00:00:15 [2/12/125] [bsp-x86_64-generic] No /src/tmp/tmp7pIFIw/etc/ld.so.conf, not running ldconfig 
16-06-03 00:00:15 [2/12/125] [bsp-x86_64-generic] Defined build system is manual
16-06-03 00:00:15 [2/12/125] [bsp-x86_64-generic] Logging build commands to /src/artifacts/bsp-x86_64-generic.62c2daccc9c8fdf7fc849ed550377937663d9013ddb203e04009e666d3e90dc5.build-log 
16-06-03 00:00:15 [2/12/125] [bsp-x86_64-generic] Elapsed time for build of bsp-x86_64-generic.62c2daccc9c8fdf7fc849ed550377937663d9013ddb203e04009e666d3e90dc5 00:00:00
16-06-03 00:00:15 [2/12/125] [bsp-x86_64-generic] Starting artifact creation 
16-06-03 00:00:15 [2/12/125] [bsp-x86_64-generic] Splitting stratum
16-06-03 00:00:17 [3/12/125] [bsp-x86_64-generic] Cached 75440 bytes 0b2bb83a8fd20e976b973d3af8053a58 as bsp-x86_64-generic.62c2daccc9c8fdf7fc849ed550377937663d9013ddb203e04009e666d3e90dc5
16-06-03 00:00:17 [3/12/125] [bsp-x86_64-generic] Elapsed time for artifact creation 00:00:01
16-06-03 00:00:17 [3/12/125] [base-system-x86_64-generic] Installing bsp-x86_64-generic splits ['bsp-x86_64-generic-runtime']
16-06-03 00:00:18 [3/12/125] [base-system-x86_64-generic] Starting build of base-system-x86_64-generic.e77ea70e71455a360ad63d5dfc00e8113cde717fc1938de56430940995b1884f 
16-06-03 00:00:18 [3/12/125] [base-system-x86_64-generic] Logging build commands to /src/artifacts/base-system-x86_64-generic.e77ea70e71455a360ad63d5dfc00e8113cde717fc1938de56430940995b1884f.build-log 
16-06-03 00:00:18 [3/12/125] [base-system-x86_64-generic] Running install-commands
16-06-03 00:00:18 [3/12/125] [base-system-x86_64-generic] Running command:
if which depmod; then (cd /lib/modules && for version in *; do depmod -a "$version"; done) fi 
Traceback (most recent call last):
  File "/src/ybd/ybd/sandbox.py", line 173, in run_sandboxed
    env=env, **config)
  File "/usr/local/lib/python2.7/dist-packages/sandboxlib/chroot.py", line 227, in run_sandbox_with_redirection
    exit, out, err = run_sandbox(command, **sandbox_config)
  File "/usr/local/lib/python2.7/dist-packages/sandboxlib/chroot.py", line 223, in run_sandbox
    raise exception
LookupError: unknown encoding: string-escape
16-06-03 00:00:18 [3/12/125] [SANDBOX] ERROR: in run_sandbox_with_redirection 99
16-06-03 00:00:18 [3/12/125] [base-system-x86_64-generic] ERROR: command failed in directory /src/definitions:

 sh -c 'if which depmod; then (cd /lib/modules && for version in *; do depmod -a "$version"; done) fi'
GIT_NO_REPLACE_OBJECTS=1
HOME=/root
LANG=en_US.UTF-8
LESSCLOSE=/usr/bin/lesspipe %s %s
LESSOPEN=| /usr/bin/lesspipe %s
LOGNAME=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
MAIL=/var/mail/root
OLDPWD=/src
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin:/usr/sbin:/usr/local/sbin
PWD=/src/definitions
SHELL=/bin/bash
SHLVL=1
SUDO_COMMAND=/bin/bash
SUDO_GID=1000
SUDO_UID=1000
SUDO_USER=vagrant
TERM=xterm-256color
TMPDIR=/src/tmp
USER=root
USERNAME=root
_=/src/ybd/ybd.py
ldconfig -r /src/tmp/tmpiP2Z53

/sbin/ldconfig.real: /usr/lib/libbz2.so.1.0 is not a symbolic link

``` ## if which depmod; then (cd /lib/modules && for version in *; do depmod -a "$version"; done) fi

CCACHE_DIR=/tmp/ccache
CCACHE_EXTRAFILES=
DEFINITIONS_REF=HEAD baserock-16.13-78-gff3a108 (baserock-16.13 + 78 commits)
DESTDIR=/base-system-x86_64-generic.inst
HOME=/tmp
LC_ALL=C
LOGNAME=tomjon
MORPH_ARCH=x86_64
PATH=/usr/lib/ccache:/usr/bin:/bin:/usr/sbin:/sbin
PREFIX=/usr
PROGRAM_REF=HEAD 16.22-3-g5a29b4d (16.22 + 3 commits)
SHELL=/bin/sh
TARGET=x86_64-baserock-linux-gnu
TARGET_STAGE1=x86_64-bootstrap-linux-gnu
TERM=dumb
TZ=UTC
USER=tomjon
USERNAME=tomjon
sh -c 'if which depmod; then (cd /lib/modules && for version in *; do depmod -a "$version"; done) fi'

16-06-03 00:00:18 [3/12/125] [base-system-x86_64-generic] ERROR: log file is at /src/artifacts/base-system-x86_64-generic.e77ea70e71455a360ad63d5dfc00e8113cde717fc1938de56430940995b1884f.build-log



16-06-03 00:00:18 [3/12/125] [base-system-x86_64-generic] ERROR: sandbox debris is at /src/tmp/tmpiP2Z53

**Comment by devcurmudgeon** [comment]
another example...

16-06-08 01:24:13 [13/409/409] [fhs-dirs] Running command:
sh ./create-fhs-dirs "$DESTDIR" 
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/67f4fb45/0/gitlab/codethink/definitions/ybd/ybd/sandbox.py", line 173, in run_sandboxed
    env=env, **config)
  File "/usr/local/lib/python2.7/dist-packages/sandboxlib/chroot.py", line 227, in run_sandbox_with_redirection
    exit, out, err = run_sandbox(command, **sandbox_config)
  File "/usr/local/lib/python2.7/dist-packages/sandboxlib/chroot.py", line 223, in run_sandbox
    raise exception
LookupError: unknown encoding: string-escape

**Comment by gtristan** [comment]
I don't have any reasonable fix for this yet, but I've gotten to the bottom of this so sharing my findings.

First problem is that sandboxlib.py does not propagate the stack trace for any exceptions in the sandbox itself when pushing the exception through the pipe here:

   https://github.com/CodethinkLabs/sandboxlib/blob/master/sandboxlib/chroot.py#L197

This of course leads to completely uninformative error messages, looking at the above mentioned error in this report, we see the stack trace of the *parent* process, and my initial reading of it tells me "raise exception" is failing to interpret a serialized exception from the child process, which is not the case.

After hacking around that and pushing the traceback through the pipe with the exception, we see the following, slightly more informative stack trace from the child process:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sandboxlib/chroot.py", line 184, in run_command_in_chroot
  File "/usr/local/lib/python2.7/dist-packages/sandboxlib/__init__.py", line 260, in _run_command
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
  File "/usr/lib/python2.7/subprocess.py", line 1339, in _execute_child
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
  File "/usr/lib/python2.7/pickle.py", line 864, in load
  File "/usr/lib/python2.7/pickle.py", line 977, in load_string
LookupError: unknown encoding: string-escape

When sandboxlib encounters an error here, it actually fails to 'pickle' the exception, because the actual chroot sandbox lacks the module:
    /usr/lib/python2.7/encodings/string_escape.py

On my machine, I have the string-escape encoding installed there, but in the sandbox where this fails, it is missing.

We are not the first to stumble on this, and it's discussed in this thread from 2011:
    https://mail.python.org/pipermail/python-list/2011-September/611815.html

First course of action, will be to fix sandboxlib probably to raise a custom exception type when the child process pushes an exception through the pipe, this would have to clearly indicate that the error message in the exception is a stack trace from the child (so as to avoid confusion when seeing an exception raised with 2 stack traces printed).

Next, I'm not entirely sure how to fix the underlying problem, it seems to me that sandboxlib is probably providing what it, itself needs to operate in a naked chroot, ideally that would be the case and we can fix it by ensuring that sandboxlib provides it's own string-escape module for itself when sandboxing.

**Comment by gtristan** [comment]
For the first issue, propagating the actual stack trace through the subprocess pipe, created the following pull request for sandboxlib:

    https://github.com/CodethinkLabs/sandboxlib/pull/18

**Comment by gtristan** [comment]
And the plot thickens...

As a workaround for missing string-escape module, I went ahead and included python2-core locally in base-system-x86_64-generic.morph, this ensures that the python2 modules which ybd is looking for are actually there... so with that we have a new stack trace with the above fix applied to sandboxlib:

16-06-11 00:02:30 [13/33/125] [base-system-x86_64-generic] Running command:
if which depmod; then (cd /lib/modules && for version in *; do depmod -a "$version"; done) fi 
Traceback (most recent call last):
  File "/store/BASEROCK/ybd/ybd/sandbox.py", line 170, in run_sandboxed
    env=env, **config)
  File "/store/BASEROCK/sandboxlib/sandboxlib/chroot.py", line 238, in run_sandbox_with_redirection
    exit, out, err = run_sandbox(command, **sandbox_config)
  File "/store/BASEROCK/sandboxlib/sandboxlib/chroot.py", line 235, in run_sandbox
    raise Exception ('Received exception from chroot, child process traceback:\n%s\n' % tb)
Exception: Received exception from chroot, child process traceback:
Traceback (most recent call last):
  File "/store/BASEROCK/sandboxlib/sandboxlib/chroot.py", line 195, in run_command_in_chroot
  File "/store/BASEROCK/sandboxlib/sandboxlib/__init__.py", line 260, in _run_command
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    except Exception:
  File "/usr/lib/python2.7/subprocess.py", line 1340, in _execute_child
    _WEXITSTATUS=os.WEXITSTATUS):
OSError: [Errno 2] No such file or directory

The above was a bit obscure, it says no such file or directory, added some additional debug printing to subprocess.py, which is trying to execute:

sh -c 'if which depmod; then (cd /lib/modules && for version in *; do depmod -a "$version"; done) fi'

HOWEVER, the following `find` invocation in the sandbox reveals:

sudo find /store/BASEROCK/build/tmp/tmpwbakvR -name sh

One match:

/store/BASEROCK/build/tmp/tmpwbakvR/usr/share/bash-completion/completions/sh

Conclusion, we cannot run these commands in the sandbox when the sandbox does not contain a shell.

**Comment by gtristan** [comment]
Finally, I looked a bit closer, and the way splitting is currently setup, this cannot work.

Artifact splitting needs to be implemented somewhere after system integration commands are run, or alternatively, system integration commands are not an option for split system artifacts.

Currently we do something like the following for each artifact we need to build:

   install_contents(component) // stages the dependencies
   build(component) // runs commands to build the artifact

Here we have a special case in install_contents() which says, if we are going to build a 'system' and splitting rules are active, then only stage some of the system; this is wrong because we need the full system, or an explicitly declared subset of the system which includes everything we're going to need in order to run the system-integration commands.

**Comment by devcurmudgeon** [comment]
Bah... I got my comment mixed up. ac41d64 fixes something else... this is still open

**Comment by devcurmudgeon** [comment]
This was fixed by installing full artifacts into sandbox, then then running the commands, then copying across the subset of content specified in the splits.

There are some glaring corner cases in this, though...

- what if the commands create additional files (which don't get copied)?
- what if the commands require binaries which (still) aren't in the sandbox, if they aren't in any of the (un-split) artifacts making up the system?
