### ISSUE TITLE
another oddity in utils...

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#228]
1 16-07-01 04:15:40 [962/1010/1010] [gnome-system-x86_64] Installing foundation artifacts ['foundation-devel', 'foundation-runtime']
Traceback (most recent call last):
  File "/src/ybd/ybd/splitting.py", line 112, in move_required_files
    copy_file_list(dn['sandbox'], dn['install'], filelist)
  File "/src/ybd/ybd/utils.py", line 220, in copy_file_list
    _process_list(srcpath, destpath, _copyfun, filelist)
  File "/src/ybd/ybd/utils.py", line 145, in _process_list
    _process_tree(destpath, srcpath, destpath, actionfunc)
  File "/src/ybd/ybd/utils.py", line 173, in _process_tree
    actionfunc)
  File "/src/ybd/ybd/utils.py", line 173, in _process_tree
    actionfunc)
  File "/src/ybd/ybd/utils.py", line 181, in _process_tree
    os.remove(destpath)
OSError: [Errno 21] Is a directory: '/src/tmp/tmpsunQMg/gnome-system-x86_64.inst/usr/share/groff/current'

**Comment by devcurmudgeon** [comment]
Shouldn't happen after reverting to Tristan's fix... so i'm closing this
