### ISSUE TITLE
fail cloning zookeeper_test

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#23]
2015-05-01 06:41:15 [zookeeper-client] WARNING: no tree from cache-server master
2015-05-01 06:41:15 [zookeeper-client] Try fetching tarball baserock_tests_zookeeper_test.tar 
Connecting to git.baserock.org (185.43.218.183:80)
wget: server returned error: HTTP/1.1 404 Not Found
2015-05-01 06:41:15 [zookeeper-client] Using git clone from  baserock:tests/zookeeper-test
2015-05-01 06:41:15 [zookeeper-client] Git repo is mirrored at /src/cache/gits/baserock_tests_zookeeper_test
2015-05-01 06:41:15 [CACHE-KEYS] Elapsed time 00:00:00
2015-05-01 06:41:15 [TOTAL] Elapsed time 00:00:03
2015-05-01 06:41:15 [systems/zookeeper-client-x86_64.morph] Finished 
Traceback (most recent call last):
  File "/src/ybd/ybd.py", line 37, in <module>
    cache.get_cache(app.settings['target'])
  File "/src/ybd/cache.py", line 102, in get_cache
    cache_key(this) + '.tar.gz')
  File "/src/ybd/cache.py", line 51, in cache_key
    hash_factors[factor] = cache_key(factor)
  File "/src/ybd/cache.py", line 51, in cache_key
    hash_factors[factor] = cache_key(factor)
  File "/src/ybd/cache.py", line 43, in cache_key
    definition['tree'] = repos.get_tree(definition)
  File "/src/ybd/repos.py", line 87, in get_tree
    with app.chdir(gitdir), open(os.devnull, "w") as fnull:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/src/ybd/app.py", line 100, in chdir
    os.chdir(dirname)
OSError: [Errno 2] No such file or directory: '/src/cache/gits/baserock_tests_zookeeper_test'

**Comment by devcurmudgeon** [comment]
fixed by 78711a6de86fad6378f8bd55b43622cfc8e2078b
