### ISSUE TITLE
Python unicode vs byte streams

### ISSUE THREAD

**Issue by leeming** [devcurmudgeon/ybd#230]
Reference to issue #218 

It is highly likely this issue will crop up again due to mixing of byte and unicode streams. Suggest to work internally with unicode with correct encoding and converting to byte streams for external use, [see here for reference](http://nedbatchelder.com/text/unipain.html).

**Comment by jjardon** [comment]
This happens to me again: https://gitlab.com/baserock/definitions/builds/2488312#down-build-trace

16-07-20 02:02:18 [43/386/386] [ca-certificates] Starting artifact creation 
16-07-20 02:02:18 [43/386/386] [ca-certificates] Splitting chunk
16-07-20 02:02:18 [43/386/386] [ca-certificates] ERROR: surprise exception in sandbox 
Traceback (most recent call last):
  File "/builds/baserock/definitions/ybd/ybd/sandbox.py", line 59, in setup
    yield
  File "/builds/baserock/definitions/ybd/ybd/assembly.py", line 74, in compose
    build(dn)     # bring in 'build-depends', and run make
  File "/builds/baserock/definitions/ybd/ybd/assembly.py", line 154, in build
    write_metadata(dn)
  File "/builds/baserock/definitions/ybd/ybd/splitting.py", line 184, in write_metadata
    write_chunk_metafile(dn)
  File "/builds/baserock/definitions/ybd/ybd/splitting.py", line 206, in write_chunk_metafile
    for p in files:
  File "/usr/local/lib/python2.7/dist-packages/fs/base.py", line 1068, in walkfiles
    for path, files in self.walk(normpath(path), wildcard=wildcard, dir_wildcard=dir_wildcard, search=search, ignore_errors=ignore_errors):
  File "/usr/local/lib/python2.7/dist-packages/fs/base.py", line 1037, in walk
    for p in recurse(path):
  File "/usr/local/lib/python2.7/dist-packages/fs/base.py", line 1030, in recurse
    for p in recurse(path):
  File "/usr/local/lib/python2.7/dist-packages/fs/base.py", line 1030, in recurse
    for p in recurse(path):
  File "/usr/local/lib/python2.7/dist-packages/fs/base.py", line 1030, in recurse
    for p in recurse(path):
  File "/usr/local/lib/python2.7/dist-packages/fs/base.py", line 1030, in recurse
    for p in recurse(path):
  File "/usr/local/lib/python2.7/dist-packages/fs/base.py", line 1029, in recurse
    for path in listdir(recurse_path, wildcard=dir_wildcard, full=True, dirs_only=True):
  File "/usr/local/lib/python2.7/dist-packages/fs/base.py", line 987, in listdir
    return self.listdir(path, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fs/errors.py", line 257, in wrapper
    return func(self,*args,**kwds)
  File "/usr/local/lib/python2.7/dist-packages/fs/osfs/__init__.py", line 268, in listdir
    return self._listdir_helper(path, paths, wildcard, full, absolute, dirs_only, files_only)
  File "/usr/local/lib/python2.7/dist-packages/fs/base.py", line 570, in _listdir_helper
    entries = [p for p in entries if isdir(pathcombine(path, p))]
  File "/usr/local/lib/python2.7/dist-packages/fs/errors.py", line 257, in wrapper
    return func(self,*args,**kwds)
  File "/usr/local/lib/python2.7/dist-packages/fs/osfs/__init__.py", line 254, in isdir
    return _isdir(self.getsyspath(path))
  File "/usr/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 113-114: ordinal not in range(128)

**Comment by devcurmudgeon** [comment]
@jjardon please can you retry with master?

**Comment by devcurmudgeon** [comment]
@jjardon I think this is fixed, in 625060baee694002c5c17597cdc7abc14b624029
