### ISSUE TITLE
cache server Broken pipe error

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#25]
192.168.56.101 - - [10/May/2015 09:45:36] code 404, message File not found
192.168.56.101 - - [10/May/2015 09:45:36] "GET /libexpat@e41f0ee70cbfb200056d9f6d10c016dea3aa7b5f2208b1608b0dc0cb7e6b3700 HTTP/1.1" 404 -
ERROR:root:Host: 192.168.56.101:8000
User-Agent: Wget
Connection: close

192.168.56.101 - - [10/May/2015 09:45:36] code 404, message File not found
192.168.56.101 - - [10/May/2015 09:45:36] "GET /cmake@529341f9dc1ee0eeac26058f8a7594217f0ba5278430ac4096f00b2202c61462 HTTP/1.1" 404 -
----------------------------------------
Exception happened during processing of request from ('192.168.56.101', 55569)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------

**Comment by devcurmudgeon** [comment]
cache server is not used at the moment
