### ISSUE TITLE
ugly error when running on systems/base-system-x86_64-generic.morph

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#45]
2015-06-02 20:29:47 [syslinux] Running install-commands
2015-06-02 20:29:47 [syslinux] Running command:
make INSTALLROOT="$DESTDIR" install 
2015-06-02 20:29:52 [syslinux] Creating cache artifact 
2015-06-02 20:29:53 [syslinux] Now cached as syslinux.982e95896929b4d2fe5a53693eef7cccac522cdd8476de039f3f70dc5cdb1c66
2015-06-02 20:29:53 [syslinux] Elapsed time 00:01:12
2015-06-02 20:29:53 [bsp-x86_64-generic] Installing syslinux.982e95896929b4d2fe5a53693eef7cccac522cdd8476de039f3f70dc5cdb1c66 
2015-06-02 20:29:53 [bsp-x86_64-generic] Start build 
2015-06-02 20:29:53 [bsp-x86_64-generic] Logging build commands to /src/cache/ybd-artifacts/bsp-x86_64-generic.5dbd2fe334a23fb1ffdf5a303aa70420641cf0a52f57147241091b801192c664.build-log 
2015-06-02 20:29:53 [bsp-x86_64-generic] Creating cache artifact 
2015-06-02 20:29:53 [bsp-x86_64-generic] Now cached as bsp-x86_64-generic.5dbd2fe334a23fb1ffdf5a303aa70420641cf0a52f57147241091b801192c664
2015-06-02 20:29:53 [bsp-x86_64-generic] Elapsed time 00:08:55
2015-06-02 20:29:53 [base-system-x86_64-generic] Installing bsp-x86_64-generic.5dbd2fe334a23fb1ffdf5a303aa70420641cf0a52f57147241091b801192c664 
2015-06-02 20:29:54 [base-system-x86_64-generic] Start build 
2015-06-02 20:29:54 [base-system-x86_64-generic] Logging build commands to /src/cache/ybd-artifacts/base-system-x86_64-generic.86046cef64ad368a1ce3078f6b2cee85bbe36a6f774a51cb7990a81ff3c59c02.build-log 
2015-06-02 20:29:54 [base-system-x86_64-generic] Running install-commands
2015-06-02 20:29:54 [base-system-x86_64-generic] Running command:
update-ca-certificates 
2015-06-02 20:29:54 [base-system-x86_64-generic] Elapsed time 01:01:53
2015-06-02 20:29:54 [TOTAL] Elapsed time 01:01:57
2015-06-02 20:29:54 [systems/base-system-x86_64-generic.morph] Finished 
Traceback (most recent call last):
  File "/src/ybd/ybd.py", line 47, in <module>
    assemble(app.settings['target'])
  File "/src/ybd/assembly.py", line 100, in assemble
    build(this)
  File "/src/ybd/assembly.py", line 131, in build
    allow_parallel=('build' in build_step))
  File "/src/ybd/sandbox.py", line 229, in run_sandboxed
    env=env, **sandbox_config)
  File "/usr/lib/python2.7/site-packages/sandboxlib/linux_user_chroot.py", line 301, in run_sandbox_with_redirection
    exit, out, err = run_sandbox(command, **sandbox_config)
  File "/usr/lib/python2.7/site-packages/sandboxlib/linux_user_chroot.py", line 289, in run_sandbox
    filesystem_root, filesystem_writable_paths)
  File "/usr/lib/python2.7/site-packages/sandboxlib/linux_user_chroot.py", line 235, in process_writable_paths
    assert writable_paths == 'none'
AssertionError

**Comment by devcurmudgeon** [comment]
fixed by c53c2700b870c14b65cf0263ee629fa956793e47
