### ISSUE TITLE
Subsystems in cluster definitions are neither built or deployed

### ISSUE THREAD

**Issue by ColdrickSotK** [devcurmudgeon/ybd#57]
Running `ybd clusters/release.morph` doesn't work. First I get an issue about INITRAMFS_PATH not existing, which is because ybd attempts to deploy the system before it has deployed the initramfs subsystem. Fixing that (and catching an error when running check extensions) gives the following output.

    2015-06-08 14:40:46 [systems-initramfs-x86_64.morph] Starting deployment 
    2015-06-08 14:41:22 [initramfs-x86_64] Running check extension: initramfs
    2015-06-08 14:41:22 [initramfs-x86_64] Couldn't find a check extension for initramfs
    2015-06-08 14:41:22 [initramfs-x86_64] Extracting system artifact 
    2015-06-08 14:41:22 [systems-initramfs-x86_64.morph] Elapsed time 00:00:35
    2015-06-08 14:41:22 [release] Elapsed time 00:08:28
    2015-06-08 14:41:22 [TOTAL] Elapsed time 00:08:32
    2015-06-08 14:41:22 [clusters/release.morph] Finished 
    Traceback (most recent call last):
      File "/root/ybd/ybd.py", line 52, in <module>
        deploy(app.settings['target'])
      File "/root/ybd/assembly.py", line 39, in deploy
        deploy(subsystem)
      File "/root/ybd/assembly.py", line 56, in deploy
        with open(cache.get_cache(system), "r") as artifact:
    TypeError: coercing to Unicode: need string or buffer, bool found

This weird error is because cache.get_cache(system) is returning False, because the subsystem wasn't built in the first place.

**Comment by ColdrickSotK** [comment]
Note I'm looking at fixing this now.

**Comment by devcurmudgeon** [comment]
On 2015-06-08 16:18, Adam Coldrick wrote:
> Note I'm looking at fixing this now.

Great! Thanks Adam :)

**Comment by devcurmudgeon** [comment]
fixed by Adam's patches at ff4b1ed8f997bf771701cc6a96d85d0082cc42fa I believe
