### ISSUE TITLE
strip-gplv3.configure extension has no attribute 'runcmd'

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#67]
2015-06-10 19:25:28 [genivi-baseline-system-x86_64-generic] Running configure extension: strip-gplv3
Traceback (most recent call last):
  File "/src/tmp/tmpsU1Eec", line 105, in <module>
    StripGPLv3ConfigureExtension().run(sys.argv[1:])
  File "/src/tmp/tmpsU1Eec", line 62, in run
    artifacts = self.runcmd(['find', meta_dir,  '-regex', regex])
AttributeError: 'StripGPLv3ConfigureExtension' object has no attribute 'runcmd'

2015-06-10 19:25:28 [genivi-baseline-system-x86_64-generic] ERROR: configure extension failed: /src/workspace/reference/baserock/baserock/definitions/extensions/strip-gplv3.configure

**Comment by ColdrickSotK** [comment]
Is this using my branch of definitions which removes dependencies? If so, it's a problem in that branch rather than ybd.

**Comment by devcurmudgeon** [comment]
i think so, thanks!
