### ISSUE TITLE
Nightly build failed, possibly due to .tar error

### ISSUE THREAD

**Issue by ssssam** [devcurmudgeon/ybd#86]
I've been running continuous YBD builds. After one successful build of commit 5e78bb70d43d4adf of definitions.git with commit c39bf7b362d5880 of YBD, a second build of the exact same thing failed. These are the last 100 lines of the log:

```
2015-06-18 20:47:23 [ncurses] Starting assembly
2015-06-18 20:47:23 [ncurses] Installing build-essential.d47d41bb446a726ba3695cb
ff7ac71723eb4289f05d6f140bb4a3bf2ad40aada
2015-06-18 20:47:23 [ncurses] Start build
2015-06-18 20:47:24 [ncurses] Git checkout upstream:ncurses in /home/build/tmp/t
mpCjK0Y2/ncurses.build
2015-06-18 20:47:24 [ncurses] Upstream version f67398af ncurses-5.9-20150131 (nc
urses-5.9-20150131 + 0 commits)
2015-06-18 20:47:24 [ncurses] Logging build commands to /home/build/artifacts/nc
urses.6c9568482f231c4373ddd22a60cfa6ffde312a4e8623e47fe73e8845b4ea708f.build-log
2015-06-18 20:47:24 [ncurses] Running configure-commands
2015-06-18 20:47:24 [ncurses] Running command:
LDCONFIG=true ./configure --with-shared --without-debug --enable-widec
2015-06-18 20:47:36 [ncurses] Running build-commands
2015-06-18 20:47:36 [ncurses] Running command:
make
2015-06-18 20:48:20 [ncurses] Running install-commands
2015-06-18 20:48:20 [ncurses] Running command:
make  DESTDIR="$DESTDIR" install
2015-06-18 20:48:25 [ncurses] Running post-install-commands
2015-06-18 20:48:25 [ncurses] Running command:
# lfs recommends some alterations for software that looks for
# libcurses instead of libncurses
# it's more convenient to have this in a separate file than the
# morph as less strings have to be escaped and comments are possible
# some software expects to find libcurses in /lib
mkdir -p "$DESTDIR/lib"
mv "$DESTDIR"/"$PREFIX"/lib/libncursesw.so.5* "$DESTDIR"/lib
ln -sf ../../lib/libncursesw.so.5 "$DESTDIR"/"$PREFIX"/lib/libncursesw.so
# some linker tricks for libraries that look for non-wide character
# versions of ncurses
for lib in ncurses form panel menu; do
# remove non-wide shared object
rm -f "$DESTDIR/${PREFIX}/lib/lib${lib}.so"
# use a linker scriptar: can't create directory './usr/lib/terminfo': No such fi
le or directory
tar: can't make dir ./usr/lib/terminfo/1: No such file or directory
tar: can't create directory './usr/lib/terminfo/': No such file or directory
tar: can't remove old file ./usr/lib/terminfo/: Not a directory
tar: write: Broken pipe
t to find the wide character variant
echo "INPUT(-l${lib}w)" >"$DESTDIR/${PREFIX}/lib/lib${lib}.so"
# symlink the non-shared library
ln -sf "lib${lib}w.a" "$DESTDIR/${PREFIX}/lib/lib${lib}.a"
done
ln -sf libncurses++w.a "$DESTDIR/${PREFIX}/lib/libncurses++.a"
# redirect software that looks for libcurses
rm -f "$DESTDIR/${PREFIX}/lib/libcursesw.so"
echo "INPUT(-lncursesw)" >"$DESTDIR/${PREFIX}/lib/libcursesw.so"
ln -sf libncurses.so "$DESTDIR/${PREFIX}/lib/libcurses.so"
ln -sf libncursesw.a "$DESTDIR/${PREFIX}/lib/libcursesw.a"
ln -sf libncurses.a "$DESTDIR/${PREFIX}/lib/libcurses.a"
# install documentation
mkdir -p "$DESTDIR/${PREFIX}/share/doc/ncurses"
cp -R doc/* "$DESTDIR/${PREFIX}/share/doc/ncurses"
# remove 'clear' and 'reset' executables, busybox provides them
rm -f "$DESTDIR/${PREFIX}/bin/clear" "$DESTDIR/${PREFIX}/bin/reset"
2015-06-18 20:48:26 [ncurses] Running strip-commands
2015-06-18 20:48:26 [ncurses] Running command:
find "$DESTDIR" -type f \
'(' -perm -111 -o -name '*.so*' -o -name '*.cmxs' -o -name '*.node' ')' \
-exec sh -ec \
'read -n4 hdr <"$1" # check for elf header
if [ "$hdr" != "$(printf \\x7fELF)" ]; then
exit 0
fi
debugfile="$DESTDIR$PREFIX/lib/debug/$(basename "$1")"
mkdir -p "$(dirname "$debugfile")"
objcopy --only-keep-debug "$1" "$debugfile"
chmod 644 "$debugfile"
strip --remove-section=.comment --remove-section=.note --strip-unneeded "$1"
objcopy --add-gnu-debuglink "$debugfile" "$1"' - {} ';'
2015-06-18 20:48:26 [ncurses] Creating cache artifact
2015-06-18 20:48:30 [ncurses] Now cached as ncurses.6c9568482f231c4373ddd22a60cfa6ffde312a4e8623e47fe73e8845b4ea708f
2015-06-18 20:48:30 [ncurses] Cleaned up /home/build/tmp/tmpCjK0Y2
2015-06-18 20:48:30 [ncurses] Elapsed time 00:01:07
2015-06-18 20:48:30 [texinfo-tarball] Installing ncurses.6c9568482f231c4373ddd22a60cfa6ffde312a4e8623e47fe73e8845b4ea708f
2015-06-18 20:48:31 [ncurses] ERROR: Problem unpacking /home/build/artifacts/ncurses.6c9568482f231c4373ddd22a60cfa6ffde312a4e8623e47fe73e8845b4ea708f
2015-06-18 20:48:31 [texinfo-tarball] Elapsed time 01:31:28
2015-06-18 20:48:31 [automake] Elapsed time 01:31:29
2015-06-18 20:48:31 [help2man] Elapsed time 01:31:29
2015-06-18 20:48:31 [bison] Elapsed time 01:31:29
2015-06-18 20:48:31 [core] Elapsed time 01:31:29
2015-06-18 20:48:31 [nasm] Elapsed time 01:31:29
2015-06-18 20:48:31 [syslinux] Elapsed time 01:31:29
2015-06-18 20:48:31 [bsp-x86_64-generic] Elapsed time 01:31:29
2015-06-18 20:48:31 [build-system-x86_64] Elapsed time 01:31:29
2015-06-18 20:48:31 [TOTAL] Elapsed time 01:31:37
2015-06-18 20:48:31 [systems/build-system-x86_64.morph] Finished
Traceback (most recent call last):
File "/home/build/run-ybd.py", line 93, in <module>
cwd=definitions_dir)
File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/build/ybd/ybd.py', 'systems/build-system-x86_64.morph']' returned non-zero exit status 1
ybd-continuous.service: main process exited, code=exited, status=1/FAILURE
Unit ybd-continuous.service entered failed state.
ybd-continuous.service failed.
```

I'm not sure exactly what has gone wrong. `tar tf /home/build/artifacts/ncurses.6c9568482f231c4373ddd22a60cfa6ffde312a4e8623e47fe73e8845b4ea708f` doesn't pick up any errors, so I don't think the artifact itself has got corrupted. I'm suspicious about the error messages from `tar` being mixed in with the build output from 'ncurses', but this could be due to stderr and stdout not being treated properly. 

I see the same error in the log happened about 16:30 with the ncurses chunk, so I think it is something specific to the ncurses chunk. However, between those two errors was a successful build of the whole system. It may that YBD's random build order means that the error is only triggered some of the time.

**Comment by ssssam** [comment]
```
# tar -C /tmp/artifacttest/ -x -f /home/build/artifacts/ncurses.6c95
68482f231c4373ddd22a60cfa6ffde312a4e8623e47fe73e8845b4ea708f 
tar: can't create directory './usr/lib/terminfo': No such file or directory
tar: can't make dir ./usr/lib/terminfo/1: No such file or directory
tar: can't create directory './usr/lib/terminfo/': No such file or directory
tar: can't remove old file ./usr/lib/terminfo/: Not a directory
```

So there is something wrong with the ncurses artifact.

**Comment by ssssam** [comment]
The issue is that .`/usr/lib/terminfo` is a relative symlink to `../share/terminfo`, but now that the contents of the tar file are sorted alphabetically,. `/usr/share/terminfo` doesn't exist at the time that the contents of `/usr/lib/terminfo` are extracted. Hence these errors. This must be caused by c39bf7b362d5880209b4c042a3072176130605ff
