### ISSUE TITLE
build-system triggers cache error

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#9]
2015-03-30 10:36:57 [CACHE-KEYS] Calculating 
2015-03-30 10:36:57 [CACHE-KEYS] Elapsed time 00:00:00
2015-03-30 10:36:57 [TOTAL] Elapsed time 00:00:02
2015-03-30 10:36:57 [build-system-x86_64-generic] Finished 
Traceback (most recent call last):
  File "/src/ybd/ybd.py", line 37, in <module>
    cache.get_cache(target)
  File "/src/ybd/cache.py", line 95, in get_cache
    cache_key(this) + '.tar.gz')
  File "/src/ybd/cache.py", line 37, in cache_key
    if definition.get('cache'):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by devcurmudgeon** [comment]
this happened if the definition provided on the command line is not found. fixed by 4c7c69a
