### ISSUE TITLE
meta files should be json

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#96]
@ColdrickSotK  said: As far as I can see, this is the only actual failure in the log. This
happens because the strip-gplv3.configure extension expects that the
chunk metadata files are formatted as JSON, but ybd's chunk metadata
files are not.

> 15-06-29 00:23:56 [635/649/649] [genivi-baseline-system-x86_64-generic] 
Running configure extension: strip-gplv3
Traceback (most recent call last):
File "/src/tmp/tmpo3mkM8", line 106, in <module>
StripGPLv3ConfigureExtension().run(sys.argv[1:])
File "/src/cida/definitions/extensions/writeexts.py", line 226, in 
run
self.process_args(args)
File "/src/tmp/tmpo3mkM8", line 67, in process_args
self.remove_chunk(target_root, artifact, chunk[1])
File "/src/tmp/tmpo3mkM8", line 76, in remove_chunk
chunk_meta_data = json.load(f)
File "/usr/lib/python2.7/json/__init__.py", line 290, in load
**kw)
File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

> 15-06-29 00:23:56 [635/649/649] [genivi-baseline-system-x86_64-generic] 
ERROR: configure extension failed: 
/src/cida/definitions/extensions/strip-gplv3.configure

**Comment by devcurmudgeon** [comment]
As of 16.05, metafiles are son
